import type { NextPage } from 'next';
import Link from 'next/link';
import Header from '../components/HeaderInner';
import Footer from '../components/Footer';
import Bottom from '../components/Bottom';
import Head from 'next/head';
import Image from 'next/image';
import wood from "../shared/assets/img/home/elagage1.png";
import FeuDeBois from "../shared/assets/img/bois-de-chauffage/bois-de-chauffage.png";
// import Banner from "../shared/assets/img/bois-de-chauffage/banner.png";
import MiniPelle from "../shared/assets/img/home/home-mini-pelle.png";
import Img2 from "../shared/assets/img/home/bois.jpg";
import PictoCourt from "../shared/assets/img/bois-de-chauffage/court.svg";
import PictoDurable from "../shared/assets/img/bois-de-chauffage/durable.svg";
import PictoLocal from "../shared/assets/img/bois-de-chauffage/local.svg";
import PictoRenouvelable from "../shared/assets/img/bois-de-chauffage/renouvelable.svg";
import PhoneRight from "../components/PhoneRight";
import BackgroundIcon from "../shared/assets/img/icon.svg";

// import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className='wrapper'>
      <Head>
        <title>FJ Elagage - Elagage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
        />
      </Head>
      <BackgroundIcon className="background-icon bois"/>

      <Header />

      <div className='inner-banner' style={{ background: "no-repeat center / cover url('/img/bois-de-chauffage/banner.png')" }}>
        <h1>Chêne et mélange livré dans les Landes</h1>
      </div>

      <div className="main mt-5">
        {/* Intro */}
          <div className="container row justify-content-center">
            <div className="col-md-12 order-md-2 p-s d-flex flex-column justify-content-center">
              <p className="intro">Le bois de chauffage reste à l'heure actuelle l'un des systèmes de chauffage les plus en vogue. FJ Elagage s'engage à vous livrer dans les délais les plus court. Bien qu'en stock la grande majorité de l'année n'attendez pas le dernier moment pour commander ! Un hiver se prépare à l'avance !</p>
              {/* <Link href="/elagage"><button type="button" className="btn btn-secondary">En savoir plus</button></Link> */}
            </div>
          </div>

        <div className="container-fluid py-md-3">
          <div className="container row align-items-center justify-content-center">
            <div className="col-md-8 order-md-2 mb-m ps-md-5 d-flex flex-column justify-content-center">
              <h2>Les avantages du bois de chauffage</h2>
              <p>Malgré une augmentation générale des prix, le bois de chauffage reste plus économique que le gaz, l’électrique ou le fioul. Le bois a le <strong>prix du combustible le plus bas du marché</strong>.</p>
              <p>La chaleur qu’il procure apporte un environnement plus chaleureux à votre foyer.
                De part sa simplicité d’utilisation, le chauffage au bois constitue le système de chauffage privilégié pour beaucoup de Français.</p>
              <p>En dépit de sa production de gaz carbonique lors de sa combustion, le chauffage au bois est plus écologique… le bois consomme de grande quantité de CO2 toute au long de sa croissance. Ce qui rapproche son bilan carbone de la neutralité.</p>
              {/* <Link href="/elagage"><button type="button" className="btn btn-secondary">En savoir plus</button></Link> */}
            </div>
            <div className="col-md-4 order-md-1 mb-md-m pr-0 ">
              <Image src={FeuDeBois} alt="..." width="100%" height="100%" layout="responsive" objectFit='cover' />
            </div>
          </div>
        </div>

        <div className="container-fluid d-flex flex-column py-m">
          <span style={{ textAlign: 'center', fontSize: '20px' }}>Le circuit est :</span>
          <div className="container pictos-wood">
            <div className="col-md-3 d-flex justify-content-center align-items-center picto-container"><PictoCourt className="picto" /><span className="text">Court</span></div>
            <div className="col-md-3 d-flex justify-content-center align-items-center picto-container"><PictoLocal className="picto" /><span className="text">Local</span></div>
            <div className="col-md-3 d-flex justify-content-center align-items-center picto-container"><PictoDurable className="picto" /><span className="text">Durable</span></div>
            <div className="col-md-3 d-flex justify-content-center align-items-center picto-container"><PictoRenouvelable className="picto" /><span className="text">Renouvelable</span></div>
          </div>
        </div>

        <div className="container-fluid py-md-3">
          <div className="container row align-items-center justify-content-center">

            <div className="col-md-6 order-md-2 mb-m ps-md-5  d-flex flex-column justify-content-center">
              <h2>Le chêne</h2>
              <p>C’est l’<strong>essence noble de nos forêts</strong>. C’est également celle de nos cheminées !
                Particulièrement recherché pour alimenter nos foyers, le chêne a la réputation de <strong>se consommer plus lentement que les autres essences</strong>, ce qui lui confère un <strong>pouvoir calorifique important</strong>. </p>
              {/* <Link href="/elagage"><button type="button" className="btn btn-secondary">En savoir plus</button></Link> */}
            </div>
            <div className="col-md-6 order-md-1 mb-md-m pr-0 ">
              <Image src={wood} alt="..." width="100%" height="60%" layout="responsive" objectFit='cover' />
            </div>
          </div>
        </div>
        <div className="container-fluid py-md-3">
          <div className="container row align-items-center justify-content-center">

            <div className="col-md-6 order-md-1 mb-m pe-md-5  d-flex flex-column justify-content-center">
              <h2>Le mélange</h2>
              <p><strong>Moins coûteux que le chêne mais tout aussi efficace</strong>, le mélange a la particularité de combiner différentes essences de bois.</p>

              <p>Cette particularité lui donne <strong>l’avantage d’utiliser différentes propriétés physique de chacune</strong>. Le chêne n’est pas un bon bois d’allumage. Couplé avec du bois blanc et du chataignier votre allumage sera plus homogène.</p>

              <p>Les essences de bois diffèrent suivant la saison.</p>

              <p>liste des essences</p>
              {/* <Link href="/elagage"><button type="button" className="btn btn-secondary">En savoir plus</button></Link> */}
            </div>
            <div className="col-md-6 order-md-2 mb-md-m pr-0 ">
              <Image src={wood} alt="..." width="100%" height="60%" layout="responsive" objectFit='cover' />
            </div>
          </div>
        </div>

        <div className="container-fluid py-md-3" id="tarifs-bois">
          <div className="container row align-items-stretch justify-content-start">

            <div className="col-md-12 order-md-1 d-flex flex-column justify-content-center">
              <h2>Tarifs</h2>
            </div>
            <div className="col-md-6 order-md-1 px-m pt-0 pb-m d-flex flex-column justify-content-flex-start">

              <h3>Nos tarifs actuels</h3>
              <table className="tarifs">
                <thead>
                  <tr>
                    <th>Prix du stère (TTC)</th>
                    <th>Chêne</th>
                    <th>Mélange</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>En 33cm</td>
                    <td>75€</td>
                    <td>65€</td>
                  </tr>
                  <tr>
                    <td>En 40cm</td>
                    <td>72€</td>
                    <td>62€</td>
                  </tr>
                  <tr>
                    <td>En 50cm</td>
                    <td>70€</td>
                    <td>60€</td>
                  </tr>
                </tbody>
              </table>
            </div>
            <div className="col-md-6 order-md-1  ps-md-5  d-flex flex-column justify-content-center">
              <h3>Livraison</h3>
              <p><strong>La livraison est gratuite</strong> dans un périmètre acceptable.</p>
              <p>Compte tenu des cours actuels, <strong>nous ne livrons pas moins de 5 stères</strong>.</p>
              {/* <p>Pour plus d’infos, merci de <Link href="/contact">nous contacter</Link></p> */}
              <Link href="/contact"><button type="button" className="btn btn-secondary">Je réserve</button></Link>
            </div>
          </div>
        </div>

        <div className="container-fluid">
          <div className="container row pb-m justify-content-center">

            <div className="col-md-6 order-md-1 pe-md-5 d-flex flex-column ">
              <h3>Calculer un stère de bois</h3>
              <p>Un stère correspond à 1m3 de bois coupé en 1m. <strong>Plus la taille des buches est petite, plus la taille de la stère est petite</strong> car les buches s’agencent mieux entre elle.</p>
              <p><strong>La quantité de bois reste la même</strong>.</p>
              <p>A titre d’exemple, une stère coupée en :</p>
              <ul>
                <li>50 cm représente 0,8m3 (1 / 1,25)</li>
                <li>40 cm représente 0,74m3 (1 / 1,36)</li>
                <li>33 cm représente 0,7m3 (1 / 1,43)</li>
              </ul>
              {/* <Link href="/elagage"><button type="button" className="btn btn-secondary">En savoir plus</button></Link> */}
            </div>
            <div className="col-md-6 order-md-1 pt-m mb-m ps-md-5  d-flex flex-column justify-content-flex-start">

              <p>Tableau des coefficients</p>
              <table className="tarifs">
                <thead>
                  <tr>
                    <th>Longueur des bûches</th>
                    <th>Coefficient calculateur</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>1 Mètre</td>
                    <td>1</td>
                  </tr>
                  <tr>
                    <td>50 cm</td>
                    <td>1,25</td>
                  </tr>
                  <tr>
                    <td>45 cm</td>
                    <td>1,30</td>
                  </tr>
                  <tr>
                    <td>40 cm</td>
                    <td>1,36</td>
                  </tr>
                  <tr>
                    <td>33 cm</td>
                    <td>1,43</td>
                  </tr>
                  <tr>
                    <td>30 cm</td>
                    <td>1,52</td>
                  </tr>
                  <tr>
                    <td>25 cm</td>
                    <td>1,67</td>
                  </tr>
                  <tr>
                    <td>20 cm</td>
                    <td>1,76</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>

      </div>
    </div >
  )
}

export default Home
