import type { NextPage } from 'next';
import Header from '../components/Header';
import Footer from '../components/Footer';
import Bottom from '../components/Bottom';
import Head from 'next/head'
import Image from 'next/image'
import wood from "../shared/assets/img/home/home-bg-fg.jpg";
import Img2 from "../shared/assets/img/home/bois.jpg";
// import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className='wrapper'>
      <Head>
        <title>FG Elagage - Bois de chauffage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
        />
      </Head>
      <Header />
      <div className='home-banner mb-xl'>
        <Image src={wood} alt="..." layout="responsive" objectFit="cover" objectPosition="center" />
      </div>

      <div className="container mb-xl">
        <div className="row align-items-stretch justify-content-center">

          <div className="col-md-6  mb-m">
            <h2>En savoir</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In eleifend tempus ex, ut ornare magna semper vel. Aliquam at vehicula mauris. Nunc sed felis tristique, dignissim ex ut, sollicitudin turpis. Integer malesuada vulputate augue sed molestie. Suspendisse eget diam lacus. Nulla gravida tellus quis erat malesuada tempus. Integer sit amet aliquam sem. Sed nunc enim, hendrerit at felis quis, iaculis consequat nisi. Integer eleifend felis in diam suscipit, sit amet mollis ligula sollicitudin. Cras dapibus id dui eget mattis. Donec mattis turpis eget felis rutrum, lobortis semper lacus finibus. Suspendisse tempus eu felis sed consectetur. Praesent tempus rhoncus ante nec facilisis.</p>
            <button type="button" className="btn btn-primary">En savoir plus</button>
          </div>
          <div className="col-md-6  mb-m">
            <Image src={wood} alt="..." layout="responsive" objectFit='contain' />
          </div>
        </div>
      </div>
      <div className="container mb-xl">
        <div className="row align-items-stretch justify-content-center">

          <div className="col-md-6 order-md-2 mb-m">
            <h2>En savoir</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In eleifend tempus ex, ut ornare magna semper vel. Aliquam at vehicula mauris. Nunc sed felis tristique, dignissim ex ut, sollicitudin turpis. Integer malesuada vulputate augue sed molestie. Suspendisse eget diam lacus. Nulla gravida tellus quis erat malesuada tempus. Integer sit amet aliquam sem. Sed nunc enim, hendrerit at felis quis, iaculis consequat nisi. Integer eleifend felis in diam suscipit, sit amet mollis ligula sollicitudin. Cras dapibus id dui eget mattis. Donec mattis turpis eget felis rutrum, lobortis semper lacus finibus. Suspendisse tempus eu felis sed consectetur. Praesent tempus rhoncus ante nec facilisis.</p>
            <button type="button" className="btn btn-primary">En savoir plus</button>
          </div>
          <div className="col-md-6 order-md-1 mb-m">
            <Image src={Img2} alt="..." layout="responsive" objectFit='contain' />
          </div>
        </div>
      </div>


      <Footer />
      <Bottom />
      {/* <div className="nav"></div> */}
      {/* <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main> */}

      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}

export default Home
