import type { NextPage } from 'next';
import Link from 'next/link';
import Header from '../components/HeaderInner';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <div className='wrapper'>
      <Head>
        <title>FJ Elagage - Élagage</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />

      <div className='inner-banner' style={{ background: "no-repeat center / cover url('/img/mentions-legales/banner.png')" }}>
        <h1>Mentions légales</h1>
      </div>

      <div className="main">
        <div className="container-fluid py-m pt-xl">
          <div className="container row align-items-stretch justify-content-center">
            <p>Conformément aux dispositions de la loi n° 2004-575 du 21 juin 2004 pour la confiance en lposition-relative économie numérique, il est précisé aux utilisateurs du site Fj Elagage lposition-relative identité des différents intervenants dans le cadre de sa réalisation et de son suivi.</p>
            <h2>Édition du site</h2>
            <p>Le présent site <Link href="/">fjelagage.fr</Link> est édité par :</p>
            <p><strong>Fg Élagage</strong><br></br>Jérémie Faure<br></br>1120 route du bourg neuf<br></br>40400 Meilhan - France<br></br>Tél. :<a href="tel:0648182936"> 06 25 52 32 31</a></p>
            <p>Responsable de la publication : Jérémie Faure</p>
            <h2>Réalisation</h2>
            <p><strong>Zukah - Agence Digitale</strong><br></br>27 rue du trouilh<br></br>40400 Meilhan<br></br>Tél :<a href="tel:0648182936"> 06 48 18 29 36</a> </p>
            <h2>Hébergement</h2>
            <p><strong>Vercel Inc.</strong><br></br>340 S Lemon Ave #4133<br></br>Walnut, CA 91789</p>
            <h2>Conditions d’utilisation</h2>
            <p>L’utilisation du présent site implique l’acceptation pleine et entière des conditions générales d’utilisation décrites ci-après. Ces conditions d’utilisation sont susceptibles d’être modifiées ou complétées à tout moment.</p>
            <h2>Informations</h2>
            <p>Les informations et documents du site sont présentés à titre indicatif, ne revêtent pas un caractère exhaustif, et ne peuvent engager la responsabilité du propriétaire du site.</p>
            <p>Le propriétaire du site ne peut être tenu responsable des dommages directs et indirects consécutifs à l’accès au site.</p>
            {/* <h2>Interactivité</h2>
            <p>Les utilisateurs du site peuvent éventuellement y déposer du contenu, apparaissant sur le site dans des espaces dédiés (notamment via les commentaires). Le contenu déposé reste sous la responsabilité de leurs auteurs, qui en assument pleinement l’entière responsabilité juridique.</p>
            <p>Le propriétaire du site se réserve le droit de retirer sans préavis et sans justification tout contenu déposé par les utilisateurs qui ne satisferait pas à la charte déontologique du site ou à la législation en vigueur.</p> */}
            <h2>Propriété intellectuelle</h2>
            <p>Sauf mention contraire, tous les éléments accessibles sur le site (textes, images, graphismes, logo, icônes, sons, logiciels, etc.) restent la propriété exclusive de leurs auteurs, en ce qui concerne les droits de propriété intellectuelle ou les droits d’usage.</p>
            <p>Toute reproduction, représentation, modification, publication, adaptation de tout ou partie des éléments du site, quel que soit le moyen ou le procédé utilisé, est interdite, sauf autorisation écrite préalable de l’auteur.</p>
            <p>Toute exploitation non autorisée du site ou de l’un quelconque des éléments qu’il contient est considérée comme constitutive d’une contrefaçon et peut être poursuivie en justice.</p>
            <p>Les marques et logos reproduits sur le site sont déposés par les sociétés qui en sont propriétaires.</p>
            <h2>Liens</h2>
            <h3 style={{marginLeft: '30px'}}>Liens sortants</h3>
            <p>Le propriétaire du site décline toute responsabilité et n’est pas engagé par le référencement via des liens hypertextes, de ressources tierces présentes sur le réseau Internet, tant en ce qui concerne leur contenu que leur pertinence.</p>
            <h3 style={{marginLeft: '30px'}}>Liens entrants</h3>
            <p>Le propriétaire du site autorise les liens hypertextes vers l’une des pages de ce site, à condition que ceux-ci ouvrent une nouvelle fenêtre et soient présentés de manière non équivoque afin d’éviter :</p>
            <ul style={{marginLeft: '30px'}}>
              <li>tout risque de confusion entre le site citant et le propriétaire du site</li>
              <li>tout risque de confusion entre le site citant et le propriétaire du site ainsi que toute présentation tendancieuse, ou contraire aux lois en vigueur. Le propriétaire du site se réserve le droit de demander la suppression d’un lien s’il estime que le site source ne respecte pas les règles ainsi définies.</li>
            </ul>
            <h2>Confidentialité</h2>
            <p>Le site <Link href="/">Fj Elagage</Link> ne conserve pas vos données personnelles.
            </p>
        </div>
      </div>
    </div>
    </div >
  )
}

export default Home
